datanode1:
  image: uhopper/hadoop-datanode
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
     - datanode1:/hadoop/dfs/data
  environment:
     - GANGLIA_HOST=localhost
     - CORE_CONF_fs_defaultFS=hdfs://ercluster:8020
