datanode1:
  image: uhopper/hadoop-datanode
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
     - datanode1:/hadoop/dfs/data
  environment:
     - GANGLIA_HOST=localhost
     - CORE_CONF_fs_defaultFS=hdfs://ercluster:8020
datanode2:
  image: uhopper/hadoop-datanode
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
     - datanode2:/hadoop/dfs/data
  environment:
     - GANGLIA_HOST=localhost
     - CORE_CONF_fs_defaultFS=hdfs://ercluster:8020
datanode3:
  image: uhopper/hadoop-datanode
  hostname: datanode3
  container_name: datanode3
  domainname: hadoop
  net: hadoop
  volumes:
     - datanode3:/hadoop/dfs/data
  environment:
     - GANGLIA_HOST=localhost
     - CORE_CONF_fs_defaultFS=hdfs://ercluster:8020
datanode4:
  image: uhopper/hadoop-datanode
  hostname: datanode4
  container_name: datanode4
  domainname: hadoop
  net: hadoop
  volumes:
     - datanode4:/hadoop/dfs/data
  environment:
     - GANGLIA_HOST=localhost
     - CORE_CONF_fs_defaultFS=hdfs://ercluster:8020
datanode5:
  image: uhopper/hadoop-datanode
  hostname: datanode5
  container_name: datanode5
  domainname: hadoop
  net: hadoop
  volumes:
     - datanode5:/hadoop/dfs/data
  environment:
     - GANGLIA_HOST=localhost
     - CORE_CONF_fs_defaultFS=hdfs://ercluster:8020
