namenode:
  image: uhopper/hadoop-namenode
  hostname: ercluster
  container_name: ercluster
  domainname: hadoop
  net: hadoop
  volumes:
    - ercluster:/hadoop/dfs/name
  ports:
    - "50070:50070"
    - "8020:8020"
  environment:
    - GANGLIA_HOST=localhost
    - CLUSTER_NAME=ercluster
